name: Auto-label issues

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.repository == 'open-telemetry/opentelemetry-ebpf-instrumentation'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        with:
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
          include-title: 0
          include-body: 1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
